# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Newuser.create!(name: 'user-1', user_type: '1', email: 'user-1@gmail.com', password: 'userpass1', prefecture: '北海道', image: 'pc.jpg')
Newuser.create!(name: 'user-2', user_type: '1', email: 'user-2@gmail.com', password: 'userpass2', prefecture: '青森県', image: 'pc.jpg')
Newuser.create!(name: 'user-3', user_type: '1', email: 'user-3@gmail.com', password: 'userpass3', prefecture: '岩手県', image: 'pc.jpg')
Newuser.create!(name: 'user-4', user_type: '1', email: 'user-4@gmail.com', password: 'userpass4', prefecture: '宮城県', image: 'pc.jpg')
Newuser.create!(name: 'user-5', user_type: '1', email: 'user-5@gmail.com', password: 'userpass5', prefecture: '秋田県', image: 'pc.jpg')
Newuser.create!(name: 'user-6', user_type: '1', email: 'user-6@gmail.com', password: 'userpass6', prefecture: '山形県', image: 'pc.jpg')
Newuser.create!(name: 'user-7', user_type: '1', email: 'user-7@gmail.com', password: 'userpass7', prefecture: '福島県', image: 'pc.jpg')
Newuser.create!(name: 'user-8', user_type: '1', email: 'user-8@gmail.com', password: 'userpass8', prefecture: '茨城県', image: 'pc.jpg')
Newuser.create!(name: 'user-9', user_type: '1', email: 'user-9@gmail.com', password: 'userpass9', prefecture: '栃木県', image: 'pc.jpg')
Newuser.create!(name: 'user-10', user_type: '1', email: 'user-10@gmail.com', password: 'userpass10', prefecture: '群馬県', image: 'pc.jpg')
Newuser.create!(name: 'user-11', user_type: '1', email: 'user-11@gmail.com', password: 'userpass11', prefecture: '埼玉県', image: 'pc.jpg')
Newuser.create!(name: 'user-12', user_type: '1', email: 'user-12@gmail.com', password: 'userpass12', prefecture: '千葉県', image: 'pc.jpg')
Newuser.create!(name: 'user-13', user_type: '1', email: 'user-13@gmail.com', password: 'userpass13', prefecture: '東京都', image: 'pc.jpg')
Newuser.create!(name: 'user-14', user_type: '1', email: 'user-14@gmail.com', password: 'userpass14', prefecture: '神奈川県', image: 'pc.jpg')
Newuser.create!(name: 'user-15', user_type: '1', email: 'user-15@gmail.com', password: 'userpass15', prefecture: '新潟県', image: 'pc.jpg')
Newuser.create!(name: 'user-16', user_type: '1', email: 'user-16@gmail.com', password: 'userpass16', prefecture: '富山県', image: 'pc.jpg')
Newuser.create!(name: 'user-17', user_type: '1', email: 'user-17@gmail.com', password: 'userpass17', prefecture: '石川県', image: 'pc.jpg')
Newuser.create!(name: 'user-18', user_type: '1', email: 'user-18@gmail.com', password: 'userpass18', prefecture: '福井県', image: 'pc.jpg')
Newuser.create!(name: 'user-19', user_type: '1', email: 'user-19@gmail.com', password: 'userpass19', prefecture: '山梨県', image: 'pc.jpg')
Newuser.create!(name: 'user-20', user_type: '1', email: 'user-20@gmail.com', password: 'userpass20', prefecture: '長野県', image: 'pc.jpg')
Newuser.create!(name: 'user-21', user_type: '1', email: 'user-21@gmail.com', password: 'userpass21', prefecture: '岐阜県', image: 'pc.jpg')
Newuser.create!(name: 'user-22', user_type: '1', email: 'user-22@gmail.com', password: 'userpass22', prefecture: '静岡県', image: 'pc.jpg')
Newuser.create!(name: 'user-23', user_type: '1', email: 'user-23@gmail.com', password: 'userpass23', prefecture: '愛知県', image: 'pc.jpg')
Newuser.create!(name: 'user-24', user_type: '1', email: 'user-24@gmail.com', password: 'userpass24', prefecture: '三重県', image: 'pc.jpg')
Newuser.create!(name: 'user-25', user_type: '1', email: 'user-25@gmail.com', password: 'userpass25', prefecture: '滋賀県', image: 'pc.jpg')
Newuser.create!(name: 'user-26', user_type: '1', email: 'user-26@gmail.com', password: 'userpass26', prefecture: '京都府', image: 'pc.jpg')
Newuser.create!(name: 'user-27', user_type: '1', email: 'user-27@gmail.com', password: 'userpass27', prefecture: '大阪府', image: 'pc.jpg')
Newuser.create!(name: 'user-28', user_type: '1', email: 'user-28@gmail.com', password: 'userpass28', prefecture: '兵庫県', image: 'pc.jpg')
Newuser.create!(name: 'user-29', user_type: '1', email: 'user-29@gmail.com', password: 'userpass29', prefecture: '奈良県', image: 'pc.jpg')
Newuser.create!(name: 'user-30', user_type: '1', email: 'user-30@gmail.com', password: 'userpass30', prefecture: '和歌山県', image: 'pc.jpg')
Newuser.create!(name: 'user-31', user_type: '1', email: 'user-31@gmail.com', password: 'userpass31', prefecture: '鳥取県', image: 'pc.jpg')
Newuser.create!(name: 'user-32', user_type: '1', email: 'user-32@gmail.com', password: 'userpass32', prefecture: '島根県', image: 'pc.jpg')
Newuser.create!(name: 'user-33', user_type: '1', email: 'user-33@gmail.com', password: 'userpass33', prefecture: '岡山県', image: 'pc.jpg')
Newuser.create!(name: 'user-34', user_type: '1', email: 'user-34@gmail.com', password: 'userpass34', prefecture: '広島県', image: 'pc.jpg')
Newuser.create!(name: 'user-35', user_type: '1', email: 'user-35@gmail.com', password: 'userpass35', prefecture: '山口県', image: 'pc.jpg')
Newuser.create!(name: 'user-36', user_type: '1', email: 'user-36@gmail.com', password: 'userpass36', prefecture: '徳島県', image: 'pc.jpg')
Newuser.create!(name: 'user-37', user_type: '1', email: 'user-37@gmail.com', password: 'userpass37', prefecture: '香川県', image: 'pc.jpg')
Newuser.create!(name: 'user-38', user_type: '1', email: 'user-38@gmail.com', password: 'userpass38', prefecture: '愛媛県', image: 'pc.jpg')
Newuser.create!(name: 'user-39', user_type: '1', email: 'user-39@gmail.com', password: 'userpass39', prefecture: '高知県', image: 'pc.jpg')
Newuser.create!(name: 'user-40', user_type: '1', email: 'user-40@gmail.com', password: 'userpass40', prefecture: '福岡県', image: 'pc.jpg')
Newuser.create!(name: 'user-41', user_type: '1', email: 'user-41@gmail.com', password: 'userpass41', prefecture: '佐賀県', image: 'pc.jpg')
Newuser.create!(name: 'user-42', user_type: '1', email: 'user-42@gmail.com', password: 'userpass42', prefecture: '長崎県', image: 'pc.jpg')
Newuser.create!(name: 'user-43', user_type: '1', email: 'user-43@gmail.com', password: 'userpass43', prefecture: '熊本県', image: 'pc.jpg')
Newuser.create!(name: 'user-44', user_type: '1', email: 'user-44@gmail.com', password: 'userpass44', prefecture: '大分県', image: 'pc.jpg')
Newuser.create!(name: 'user-45', user_type: '1', email: 'user-45@gmail.com', password: 'userpass45', prefecture: '宮崎県', image: 'pc.jpg')
Newuser.create!(name: 'user-46', user_type: '1', email: 'user-46@gmail.com', password: 'userpass46', prefecture: '鹿児島県', image: 'pc.jpg')
Newuser.create!(name: 'user-47', user_type: '1', email: 'user-47@gmail.com', password: 'userpass47', prefecture: '沖縄県', image: 'pc.jpg')




Newuser.create!(name: 'shinkyu-1', user_type: '2', email: 'shinkyu-1@gmail.com', password: 'shinkyu1', prefecture: '北海道', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-2', user_type: '2', email: 'shinkyu-2@gmail.com', password: 'shinkyu2', prefecture: '青森県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-3', user_type: '2', email: 'shinkyu-3@gmail.com', password: 'shinkyu3', prefecture: '岩手県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-4', user_type: '2', email: 'shinkyu-4@gmail.com', password: 'shinkyu4', prefecture: '宮城県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-5', user_type: '2', email: 'shinkyu-5@gmail.com', password: 'shinkyu5', prefecture: '秋田県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-6', user_type: '2', email: 'shinkyu-6@gmail.com', password: 'shinkyu6', prefecture: '山形県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-7', user_type: '2', email: 'shinkyu-7@gmail.com', password: 'shinkyu7', prefecture: '福島県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-8', user_type: '2', email: 'shinkyu-8@gmail.com', password: 'shinkyu8', prefecture: '茨城県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-9', user_type: '2', email: 'shinkyu-9@gmail.com', password: 'shinkyu9', prefecture: '栃木県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-10', user_type: '2', email: 'shinkyu-10@gmail.com', password: 'shinkyu10', prefecture: '群馬県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-11', user_type: '2', email: 'shinkyu-11@gmail.com', password: 'shinkyu11', prefecture: '埼玉県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-12', user_type: '2', email: 'shinkyu-12@gmail.com', password: 'shinkyu12', prefecture: '千葉県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-13', user_type: '2', email: 'shinkyu-13@gmail.com', password: 'shinkyu13', prefecture: '東京都', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-14', user_type: '2', email: 'shinkyu-14@gmail.com', password: 'shinkyu14', prefecture: '神奈川県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-15', user_type: '2', email: 'shinkyu-15@gmail.com', password: 'shinkyu15', prefecture: '新潟県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-16', user_type: '2', email: 'shinkyu-16@gmail.com', password: 'shinkyu16', prefecture: '富山県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-17', user_type: '2', email: 'shinkyu-17@gmail.com', password: 'shinkyu17', prefecture: '石川県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-18', user_type: '2', email: 'shinkyu-18@gmail.com', password: 'shinkyu18', prefecture: '福井県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-19', user_type: '2', email: 'shinkyu-19@gmail.com', password: 'shinkyu19', prefecture: '山梨県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-20', user_type: '2', email: 'shinkyu-20@gmail.com', password: 'shinkyu20', prefecture: '長野県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-21', user_type: '2', email: 'shinkyu-21@gmail.com', password: 'shinkyu21', prefecture: '岐阜県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-22', user_type: '2', email: 'shinkyu-22@gmail.com', password: 'shinkyu22', prefecture: '静岡県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-23', user_type: '2', email: 'shinkyu-23@gmail.com', password: 'shinkyu23', prefecture: '愛知県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-24', user_type: '2', email: 'shinkyu-24@gmail.com', password: 'shinkyu24', prefecture: '三重県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-25', user_type: '2', email: 'shinkyu-25@gmail.com', password: 'shinkyu25', prefecture: '滋賀県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-26', user_type: '2', email: 'shinkyu-26@gmail.com', password: 'shinkyu26', prefecture: '京都府', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-27', user_type: '2', email: 'shinkyu-27@gmail.com', password: 'shinkyu27', prefecture: '大阪府', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-28', user_type: '2', email: 'shinkyu-28@gmail.com', password: 'shinkyu28', prefecture: '兵庫県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-29', user_type: '2', email: 'shinkyu-29@gmail.com', password: 'shinkyu29', prefecture: '奈良県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-30', user_type: '2', email: 'shinkyu-30@gmail.com', password: 'shinkyu30', prefecture: '和歌山県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-31', user_type: '2', email: 'shinkyu-31@gmail.com', password: 'shinkyu31', prefecture: '鳥取県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-32', user_type: '2', email: 'shinkyu-32@gmail.com', password: 'shinkyu32', prefecture: '島根県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-33', user_type: '2', email: 'shinkyu-33@gmail.com', password: 'shinkyu33', prefecture: '岡山県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-34', user_type: '2', email: 'shinkyu-34@gmail.com', password: 'shinkyu34', prefecture: '広島県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-35', user_type: '2', email: 'shinkyu-35@gmail.com', password: 'shinkyu35', prefecture: '山口県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-36', user_type: '2', email: 'shinkyu-36@gmail.com', password: 'shinkyu36', prefecture: '徳島県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-37', user_type: '2', email: 'shinkyu-37@gmail.com', password: 'shinkyu37', prefecture: '香川県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-38', user_type: '2', email: 'shinkyu-38@gmail.com', password: 'shinkyu38', prefecture: '愛媛県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-39', user_type: '2', email: 'shinkyu-39@gmail.com', password: 'shinkyu39', prefecture: '高知県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-40', user_type: '2', email: 'shinkyu-40@gmail.com', password: 'shinkyu40', prefecture: '福岡県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-41', user_type: '2', email: 'shinkyu-41@gmail.com', password: 'shinkyu41', prefecture: '佐賀県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-42', user_type: '2', email: 'shinkyu-42@gmail.com', password: 'shinkyu42', prefecture: '長崎県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-43', user_type: '2', email: 'shinkyu-43@gmail.com', password: 'shinkyu43', prefecture: '熊本県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-44', user_type: '2', email: 'shinkyu-44@gmail.com', password: 'shinkyu44', prefecture: '大分県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-45', user_type: '2', email: 'shinkyu-45@gmail.com', password: 'shinkyu45', prefecture: '宮崎県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-46', user_type: '2', email: 'shinkyu-46@gmail.com', password: 'shinkyu46', prefecture: '鹿児島県', image: 'pc.jpg')
Newuser.create!(name: 'shinkyu-47', user_type: '2', email: 'shinkyu-47@gmail.com', password: 'shinkyu47', prefecture: '沖縄県', image: 'pc.jpg') 